src/Entity/Host.php
<?php

declare(strict_types=1);

namespace App\Entity;

use App\Repository\HostRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: HostRepository::class)]
class Host extends PartyMember
{
    public function getRole(): string
    {
        return self::ROLE_HOST;
    }
}

src/Entity/PartyPackage/Party.php
<?php

declare(strict_types=1);

namespace App\Entity\PartyPackage;

use App\Repository\PartyPackage\PartyRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Types\UuidType;
use Symfony\Component\Uid\Uuid;

#[ORM\Entity(repositoryClass: PartyRepository::class)]
class Party
{
    #[ORM\Id]
    #[ORM\Column(type: UuidType::NAME, unique: true)]
    #[ORM\GeneratedValue(strategy: 'CUSTOM')]
    #[ORM\CustomIdGenerator(class: 'doctrine.uuid_generator')]
    // @phpstan-ignore-next-line
    private ?Uuid $id = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $partyDate = null;

    #[ORM\Column(length: 255)]
    private ?string $title = null;

    /**
     * @var Collection<int, PartyMember>
     */
    #[ORM\OneToMany(targetEntity: PartyMember::class, mappedBy: 'party')]
    private Collection $partyMembers;

    public function __construct()
    {
        $this->partyMembers = new ArrayCollection();
    }

    public function getId(): ?Uuid
    {
        return $this->id;
    }

    public function getPartyDate(): ?\DateTimeInterface
    {
        return $this->partyDate;
    }

    public function setPartyDate(\DateTimeInterface $partyDate): static
    {
        $this->partyDate = $partyDate;

        return $this;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): static
    {
        $this->title = $title;

        return $this;
    }

    /**
     * @return Collection<int, PartyMember>
     */
    public function getPartyMembers(): Collection
    {
        return $this->partyMembers;
    }

    public function addPartyMember(PartyMember $partyMember): static
    {
        if (!$this->partyMembers->contains($partyMember)) {
            $this->partyMembers->add($partyMember);
            $partyMember->setParty($this);
        }

        return $this;
    }

    public function removePartyMember(PartyMember $partyMember): static
    {
        if ($this->partyMembers->removeElement($partyMember)) {
            // set the owning side to null (unless already changed)
            if ($partyMember->getParty() === $this) {
                $partyMember->setParty(null);
            }
        }

        return $this;
    }
}

src/Form/Party/PartyResponseFormModel.php
<?php

declare(strict_types=1);

namespace App\Form\Party;

use App\Enum\ResponseStatus;
use Symfony\Component\Validator\Constraints as Assert;

class PartyResponseFormModel
{
    #[Assert\Range(min: 1, max: 2, notInRangeMessage: 'Bitte gib 1 oder 2 Begleitpersonen an.')]
    public ?int $plusGuests = null;

    public ?ResponseStatus $responseStatus = null;
}

src/Form/Party/PartyResponseFormType.php
<?php

declare(strict_types=1);

namespace App\Form\Party;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class PartyResponseFormType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('accept', SubmitType::class, [
                'label' => 'Zusage',
                'attr' => ['class' => 'btn btn-secondary w-100 mb-2']
            ])
            ->add('accept_with_guests', SubmitType::class, [
                'label' => 'Zusage + 1',
                'attr' => ['class' => 'btn btn-secondary w-100 mb-2']
            ])
            ->add('decline', SubmitType::class, [
                'label' => 'Absage',
                'attr' => ['class' => 'btn btn-secondary w-100']
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => PartyResponseFormModel::class,
            'csrf_protection' => true,
            'csrf_field_name' => '_token',
            'csrf_token_id'   => 'party_response_form',
        ]);
    }
}

src/Controller/PartyController.php
<?php

declare(strict_types=1);

namespace App\Controller;

use App\Entity\Party;
use App\Entity\PartyGroup;
use App\Entity\PartyNews;
use App\Entity\User;
use App\Entity\UserMessageStatus;
use App\Event\BeforeLoadDataForPartyEvent;
use App\Repository\PartyMemberRepository;
use App\Repository\PartyNewsRepository;
use App\Repository\UserMessageStatusRepository;
use App\Service\UserMessage\UserMessageManager;
use App\Service\PartyMember\PartyMembershipManager\PartyMembershipManagerInterface;
use App\Enum\ResponseStatus;
use Symfony\Component\Form\ClickableInterface;
use Psr\Log\LoggerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\EventDispatcher\EventDispatcherInterface;
use App\Form\Party\PartyResponseFormModel;
use App\Form\Party\PartyResponseFormType;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;
use Symfony\Component\Routing\Generator\UrlGeneratorInterface;
use UnexpectedValueException;
use App\Attribute\RequiresPartyAccess;

final class PartyController extends AbstractController
{
    public function __construct(
        private readonly EventDispatcherInterface $eventDispatcher,
        private readonly LoggerInterface $logger
    ) {}

    #[Route('/party/{id}', name: 'party_show')]
    #[RequiresPartyAccess]
    public function show(
        Party $party,
        PartyNewsRepository $partyNewsRepository,
        UserMessageStatusRepository $messageStatusRepository,
    ): Response {
        $user = $this->getUser();
        if (!$user instanceof User) {
            throw $this->createAccessDeniedException('Du musst eingeloggt sein, um diese Party zu sehen.');
        }

        $this->eventDispatcher->dispatch(new BeforeLoadDataForPartyEvent($user, $party));

        /** @var PartyNews[] $news */
        $news = $partyNewsRepository->findBy(
            ['party' => $party],
            ['createdAt' => 'DESC'],
            3
        );

        $userMessageStatus = $messageStatusRepository->findAllByUserAndPartyNews($user, $news);
        $statusMap = $this->getUserMessageStatusMap($userMessageStatus);

        $popupNews = [];
        try {
            $popupNews = array_filter(
                $news,
                fn(PartyNews $news) => $news->getAsPopup()  // marked as popup
                    && !($statusMap[$news->getId()?->toRfc4122()]->isRead()) // news not read
            );
        } catch (\Exception $exception) {
            $this->logger->error(
                $exception->getMessage(),
                ['id' => $user->getId(), 'party' => $party->getId(), 'exception' => $exception]
            );
        }


        return $this->render('party/show.html.twig', [
            'party' => $party,
            'news' => $news,
            'currentUser' => $user,
            'statusMap' => $statusMap,
            'popupNews' => $popupNews,
            'foodVotingGroup' => $this->getFoodVotingGroupForUser($party, $user),
        ]);
    }


    #[Route('/party/{id}/foreshadowing', name: 'party_foreshadowing')]
    #[RequiresPartyAccess(redirectIfForeshadowing: false)]
    public function foreshadowing(
        Party $party,
    ): Response {
        $user = $this->getUser();
        if (!$user instanceof User) {
            throw $this->createAccessDeniedException('Du musst eingeloggt sein, um diese Party zu sehen.');
        }
        if (!$party->isForeshadowing()) {
            return $this->redirectToRoute('party_show', ['id' => $party->getId()]);
        }

        return $this->render('party/foreshadowing.html.twig', [
            'party' => $party,
            'currentUser' => $user,
            'imagePath' => '486b7063-47a6-4b32-a234-0396406db70a.png'
        ]);
    }

    #[Route('/party/{id}/news', name: 'party_news_list')]
    #[RequiresPartyAccess]
    public function newsList(
        Party $party,
        PartyNewsRepository $partyNewsRepository,
        UserMessageStatusRepository $messageStatusRepository,
    ): Response {
        $user = $this->getUser();
        if (!$user instanceof User) {
            throw $this->createAccessDeniedException('Du musst eingeloggt sein, um diese Party zu sehen.');
        }

        $this->eventDispatcher->dispatch(new BeforeLoadDataForPartyEvent($user, $party));

        $news = $partyNewsRepository->findBy(
            ['party' => $party],
            ['createdAt' => 'DESC']
        );

        $userMessageStatus = $messageStatusRepository->findAllByUserAndPartyNews($user, $news);
        $statusMap = $this->getUserMessageStatusMap($userMessageStatus);

        return $this->render('party/news_list.html.twig', [
            'party' => $party,
            'news' => $news,
            'statusMap' => $statusMap,
        ]);
    }

    #[Route('/party/news/{id}', name: 'party_news_detail')]
    #[RequiresPartyAccess]
    public function newsDetail(
        PartyNews $news,
        UserMessageManager $userMessageManager
    ): Response {
        $user = $this->getUser();

        if (!$user instanceof User) {
            throw $this->createAccessDeniedException('Du musst eingeloggt sein, um diese Nachricht zu sehen.');
        }

        $userMessageManager->markAsRead($user, $news);

        return $this->render('party/news_detail.html.twig', [
            'news' => $news,
            'party' => $news->getParty(),
        ]);
    }

    #[Route('/party/{id}/action/response', name: 'party_action_response')]
    #[RequiresPartyAccess]
    public function manageResponse(
        Party $party,
        Request $request,
        PartyMembershipManagerInterface $partyMembershipManager,
    ): Response {
        $user = $this->getUser();
        if (!$user instanceof User) {
            throw $this->createAccessDeniedException('Du musst eingeloggt sein, um diese Party zu sehen.');
        }

        $now = new \DateTimeImmutable();
        $deadline = $party->getRsvpDeadline();
        $isRsvpOpen = $deadline === null || $deadline >= $now;

        $form = null;
        if ($isRsvpOpen) {
            $formModel = new PartyResponseFormModel();
            $form = $this->createForm(PartyResponseFormType::class, $formModel);

            $form->handleRequest($request);

            if ($form->isSubmitted() && $form->isValid()) {
                $accept = $form->get('accept');
                $acceptWithGuests = $form->get('accept_with_guests');
                $decline = $form->get('decline');

                if ($accept instanceof ClickableInterface && $accept->isClicked()) {
                    $formModel->responseStatus = ResponseStatus::ACCEPTED;
                    $formModel->plusGuests = null;
                } elseif ($acceptWithGuests instanceof ClickableInterface && $acceptWithGuests->isClicked()) {
                    $formModel->responseStatus = ResponseStatus::ACCEPTED;
                    $formModel->plusGuests = 1;
                } elseif ($decline instanceof ClickableInterface && $decline->isClicked()) {
                    $formModel->responseStatus = ResponseStatus::DECLINED;
                    $formModel->plusGuests = null;
                } else {
                    return $this->redirectToRoute('party_action_response', ['id' => $party->getId()]);
                }

                $partyMembershipManager->setResponseForUser($user, $party, $formModel);

                if ($formModel->responseStatus === ResponseStatus::ACCEPTED) {
                    $this->addFlash('success', $formModel->plusGuests ? sprintf('Deine Zusage mit %d Begleitperson(en) wurde erfasst.', $formModel->plusGuests) : 'Deine Zusage wurde erfasst.');
                } else {
                    $this->addFlash('info', 'Deine Absage wurde erfasst.');
                }

                return $this->redirectToRoute('party_action_response', ['id' => $party->getId()]);
            }
        }

        $currentDecision = null;

        // Resolve current decision for display
        $membership = null;
        try {
            $membership = $partyMembershipManager->getMembershipForUser($user, $party);
        } catch (\Throwable) {
            $membership = null;
        }

        if ($membership !== null) {
            $status = $membership->getResponseStatus();
            $extras = $membership->getExtraGuests();
            if ($status !== null) {
                $label = $status->getLabel();
                $emoji = $status === ResponseStatus::ACCEPTED ? ' 🙂' : ' 🙁';
                if ($status === ResponseStatus::ACCEPTED && $extras) {
                    $currentDecision = sprintf('%s + %d%s', $label, $extras, $emoji);
                } else {
                    $currentDecision = $label . $emoji;
                }
            }
        }


        return $this->render('party/action_response.html.twig', [
            'party' => $party,
            'currentUser' => $user,
            'isRsvpOpen' => $isRsvpOpen,
            'form' => $form?->createView(),
            'currentDecision' => $currentDecision,
        ]);
    }

    /**
     * @param UserMessageStatus[] $userMessageStatus
     * @return array<string,UserMessageStatus> mapping partyNewsId to UserMessageStatus
     */
    private function getUserMessageStatusMap(array $userMessageStatus): array
    {
        $statusMap = [];
        foreach ($userMessageStatus as $status) {
            $partyNewsId = $status->getPartyNews()?->getId();

            if ($partyNewsId === null) {
                throw new \UnexpectedValueException('id must be set.');
            }

            $statusMap[$partyNewsId->toRfc4122()] = $status;
        }

        return $statusMap;
    }

    private function getFoodVotingGroupForUser(Party $party, User $user): ?PartyGroup
    {
        // Find the user's party member record
        $partyMember = null;
        foreach ($party->getPartyMembers() as $member) {
            if ($member->getUser() === $user) {

templates/party/_actions.html.twig
<div class="d-grid gap-2">
    <a class="btn btn-primary" href="{{ path('party_action_response', { id: party.id }) }}">Zu-/Absage verwalten</a>
    <a class="btn btn-outline-secondary" href="{{ path('chat_room_self', { id: party.id }) }}">Nachricht an Host senden</a>
    
    <a class="btn btn-warning" href="{{ path('party_clash_entry', { id: party.id }) }}">
        <i class="fa fa-bolt"></i> Clash
    </a>
    
    {% if foodVotingGroup is not null %}
        <a class="btn btn-success" href="{{ path('app_food_voting', { id: foodVotingGroup.id }) }}">
            <i class="fa fa-utensils"></i> Essensplanung
        </a>
    {% endif %}
    
    <a class="btn btn-outline-success" href="{{ path('shop_list', { id: party.id }) }}">Zum Shop</a>
</div>

templates/party/_news_summary.html.twig
<div class="list-group mt-3">
    {% for item in news %}
        {% set status = statusMap[item.id ~ '']|default(null) %}
        {% set isUnread = not status or not status.isRead() %}

        <a href="{{ path('party_news_detail', {id: item.id}) }}"
           class="list-group-item list-group-item-action
                  {% if isUnread %}list-group-item-warning{% endif %}">
            <div class="d-flex justify-content-between align-items-center">
                <div class="d-flex flex-column">
                    <h5 class="mb-1">{{ item.text|striptags|u.truncate(30, '...') }}</h5>
                    <small class="text-muted mt-2">{{ item.createdAt|date('d.m.Y H:i') }}</small>
                </div>

                {% if isUnread %}
                    <span class="badge bg-warning text-dark">Neu</span>
                {% endif %}
            </div>
        </a>
    {% else %}
        <p class="text-muted">Keine Nachrichten vorhanden.</p>
    {% endfor %}
</div>

templates/party/_status.html.twig
{% set membership = party.partyMembers|filter(m => m.user == currentUser)|first %}

{% if membership %}
    <span class="badge {% if membership.responseStatus.value == 'accepted' %}bg-success{% elseif membership.responseStatus.value == 'declined' %}bg-danger{% else %}bg-secondary{% endif %}">
        {{ membership.responseStatus|response_status_label }}
    </span>
{% else %}
    <div class="alert alert-warning mt-3">
        Du bist kein Mitglied dieser Party.
    </div>
{% endif %}

templates/party/action_response.html.twig
{% extends 'base.html.twig' %}

{% block title %}Zu-/Absage verwalten{% endblock %}

{% block body %}
    <div class="container d-flex justify-content-center">
        <div class="card p-4 shadow-lg" style="max-width: 400px; width: 100%;">
            <h2 class="text-center mb-3">{{ party.title }}</h2>

            {% if not isRsvpOpen %}
                <div class="alert alert-warning">Die Zu-/Absage ist nicht mehr möglich.</div>
            {% endif %}

            {% if currentDecision %}
                <div class="alert alert-info mb-3">Aktuelle Entscheidung: {{ currentDecision }}</div>
            {% endif %}

            {% if form is defined and form %}
                {{ form_start(form) }}
                <div class="d-grid gap-2">
                    {{ form_widget(form.accept, {'attr': {'class': 'btn btn-secondary w-100'}}) }}
                    {{ form_widget(form.accept_with_guests, {'attr': {'class': 'btn btn-primary w-100'}}) }}
                    {{ form_widget(form.decline, {'attr': {'class': 'btn btn-outline-secondary w-100'}}) }}
                </div>
                {{ form_end(form) }}
            {% endif %}

            <a href="{{ path('party_show', { id: party.id }) }}" class="btn btn-link mt-3 w-100">Zurück zur Party</a>
        </div>
    </div>
{% endblock %}

templates/party/foreshadowing.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ party.title }}{% endblock %}

{% block body %}
    <section class="d-flex justify-content-center align-items-center">
        <img src="{{ asset(imagePath) }}" alt="Party Image" class="img-fluid" style="max-width: 100%; max-height: 100%;">
    </section>
{% endblock %}

templates/party/news_detail.html.twig
{% extends 'base.html.twig' %}

{% block title %}Nachricht zu {{ party.title }}{% endblock %}

{% block body %}
    <h1 class="mb-4">Nachricht für {{ party.title }}</h1>

    <div class="card shadow-sm">
        <div class="card-body d-flex flex-column">
            <h5 class="card-title">{{ news.text|raw|nl2br }}</h5>

            {% if news.media %}
                <img src="{{ path('app_media_view', {id: news.media.id}) }}"
                     class="img-fluid mt-3"
                     style="max-width: 500px; height: auto;"
                     alt="News Bild">
            {% endif %}

            <small class="text-muted mt-3">{{ news.createdAt|date('d.m.Y H:i') }}</small>
        </div>
    </div>

    <a href="{{ path('party_show', {id: party.id}) }}" class="btn btn-secondary mt-4">
        Zurück zur Party-Übersicht
    </a>
{% endblock %}

templates/party/news_list.html.twig
{% extends 'base.html.twig' %}

{% block title %}Alle Nachrichten zu {{ party.title }}{% endblock %}

{% block body %}
    <h1 class="mb-4">Alle Nachrichten für {{ party.title }}</h1>

    {% if news is empty %}
        <div class="alert alert-info">
            Es gibt noch keine Nachrichten für diese Party.
        </div>
    {% else %}
        {% include 'party/_news_summary.html.twig' with { 'news': news, 'statusMap': statusMap } %}
    {% endif %}

    <a href="{{ path('party_show', {id: party.id}) }}" class="btn btn-secondary mt-4">
        Zurück zur Übersicht
    </a>
{% endblock %}

templates/party/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ party.title }}{% endblock %}

{% block body %}
    <section class="mb-2 pb-1 border-bottom">
        <div class="d-flex justify-content-between align-items-start flex-wrap">
            <div>
                <h1 class="mb-2">{{ party.title }}</h1>
                <p class="text-muted">{{ party.partyDate|date('d.m.Y') }}</p>
            </div>

            <div class="mt-2 mt-lg-0">
                {% include 'party/_status.html.twig' with { 'party': party, 'currentUser': currentUser } %}
            </div>
        </div>
    </section>

    <section class="mb-2 pb-2 border-bottom">
        <div class="d-flex justify-content-between align-items-center mb-3">
            <h2 class="h4 m-0 text-primary">Nachrichten</h2>
            {% set membership = party.partyMembers|filter(m => m.user == currentUser)|first %}
            {% if membership and membership.role == 'Host' %}
                <a href="{{ path('chat_rooms_list', {id: party.id}) }}" class="btn btn-sm btn-outline-secondary">Alle Chats</a>
            {% endif %}
        </div>

        {% include 'party/_news_summary.html.twig' with { 'news': news, 'statusMap': statusMap } %}

        {% if news|length > 0 %}
            <a href="{{ path('party_news_list', {id: party.id}) }}" class="btn btn-link mt-3">
                ➔ Alle Nachrichten anzeigen
            </a>
        {% endif %}
    </section>

    <section class="mb-2">
        <h2 class="h4 mb-3 text-primary">Aktionen</h2>

        {% include 'party/_actions.html.twig' %}
    </section>

    {% if popupNews is not empty %}
        <div id="popupNewsModal" class="modal fade show d-block" tabindex="-1" role="dialog" aria-modal="true"
             style="background-color: rgba(0,0,0,0.5);">
            <div class="modal-dialog modal-lg modal-dialog-centered">
                <div class="modal-content shadow-lg">
                    <div class="modal-header">
                        <h5 class="modal-title">Wichtige Nachrichten</h5>
                        <button type="button" class="btn-close" aria-label="Schließen" data-close-popup></button>
                    </div>
                    <div class="modal-body" style="max-height: 70vh; overflow: auto;">
                        {% for popup in popupNews %}
                            <div class="alert alert-warning mb-3">
                                <div class="text-break">{{ popup.text|raw|nl2br }}</div>
                                <div class="d-flex justify-content-between align-items-center mt-3">
                                    <small class="text-muted">{{ popup.createdAt|date('d.m.Y H:i') }}</small>
                                    <a href="{{ path('party_news_detail', {id: popup.id}) }}"
                                       class="btn btn-sm btn-primary">Details ansehen</a>
                                </div>
                            </div>
                        {% else %}
                            <p class="text-muted">Keine Nachrichten vorhanden.</p>
                        {% endfor %}
                    </div>
                </div>
            </div>
        </div>
        <script>
            (function () {
                var modal = document.getElementById('popupNewsModal');
                if (!modal) return;
                var closeBtn = modal.querySelector('[data-close-popup]');
                var dismiss = function () {
                    if (modal && modal.parentNode) {
                        modal.parentNode.removeChild(modal);
                    }
                };
                if (closeBtn) {
                    closeBtn.addEventListener('click', function (e) {
                        e.preventDefault();
                        dismiss();
                    });
                }
                modal.addEventListener('click', function (e) {
                    if (e.target === modal) {
                        dismiss();
                    }
                });
                document.addEventListener('keydown', function (e) {
                    if (e.key === 'Escape' || e.key === 'Esc') {
                        dismiss();
                    }
                }, {once: true});
            })();
        </script>
    {% endif %}
{% endblock %}